# Generated by Django 4.0.5 on 2022-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation_app', '0006_alter_donation_pick_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(null=True),
        ),
    ]
