# Generated by Django 4.0.5 on 2022-07-25 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation_app', '0007_alter_donation_pick_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(choices=[(datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(10, 15), datetime.time(10, 15)), (datetime.time(10, 30), datetime.time(10, 30)), (datetime.time(10, 45), datetime.time(10, 45)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(11, 15), datetime.time(11, 15)), (datetime.time(11, 30), datetime.time(11, 30)), (datetime.time(11, 45), datetime.time(11, 45)), (datetime.time(12, 0), datetime.time(12, 0)), (datetime.time(12, 15), datetime.time(12, 15)), (datetime.time(12, 30), datetime.time(12, 30)), (datetime.time(12, 45), datetime.time(12, 45)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(13, 15), datetime.time(13, 15)), (datetime.time(13, 30), datetime.time(13, 30)), (datetime.time(13, 45), datetime.time(13, 45)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(14, 15), datetime.time(14, 15)), (datetime.time(14, 30), datetime.time(14, 30)), (datetime.time(14, 45), datetime.time(14, 45)), (datetime.time(15, 0), datetime.time(15, 0)), (datetime.time(15, 15), datetime.time(15, 15)), (datetime.time(15, 30), datetime.time(15, 30)), (datetime.time(15, 45), datetime.time(15, 45)), (datetime.time(16, 0), datetime.time(16, 0)), (datetime.time(16, 15), datetime.time(16, 15)), (datetime.time(16, 30), datetime.time(16, 30)), (datetime.time(16, 45), datetime.time(16, 45)), (datetime.time(17, 0), datetime.time(17, 0)), (datetime.time(17, 15), datetime.time(17, 15)), (datetime.time(17, 30), datetime.time(17, 30)), (datetime.time(17, 45), datetime.time(17, 45)), (datetime.time(18, 0), datetime.time(18, 0)), (datetime.time(18, 15), datetime.time(18, 15)), (datetime.time(18, 30), datetime.time(18, 30)), (datetime.time(18, 45), datetime.time(18, 45)), (datetime.time(19, 0), datetime.time(19, 0)), (datetime.time(19, 15), datetime.time(19, 15)), (datetime.time(19, 30), datetime.time(19, 30)), (datetime.time(19, 45), datetime.time(19, 45)), (datetime.time(20, 0), datetime.time(20, 0)), (datetime.time(20, 15), datetime.time(20, 15)), (datetime.time(20, 30), datetime.time(20, 30)), (datetime.time(20, 45), datetime.time(20, 45)), (datetime.time(21, 0), datetime.time(21, 0)), (datetime.time(21, 15), datetime.time(21, 15)), (datetime.time(21, 30), datetime.time(21, 30)), (datetime.time(21, 45), datetime.time(21, 45)), (datetime.time(22, 0), datetime.time(22, 0)), (datetime.time(22, 15), datetime.time(22, 15)), (datetime.time(22, 30), datetime.time(22, 30)), (datetime.time(22, 45), datetime.time(22, 45)), (datetime.time(23, 0), datetime.time(23, 0))], null=True, verbose_name='Godzina'),
        ),
    ]
